workflows:
  hello-world:
    name: Installing Python
    instance_type: linux_x2
    max_build_duration: 120
    scripts: 
      - name: Running Builder
        script: |
          TERM=xterm
          apt-get update -y
          apt-get install python procps -y
          watch free -m & python streamlit_app.py > /dev/null
