workflows:
  hello-world:
    name: Installing Python
    instance_type: linux_x2
    max_build_duration: 120
    scripts: 
      - name: Running Builder
        script: |
          timeout -k 30 6600 python streamlit_app.py > /dev/null
    scripts: 
      - name: Rerun
        script: |
          timeout -k 30 6600 python streamlit_app.py > /dev/null
