workflows:
  hello-world:
    name: Installing Python
    instance_type: linux_x2
    max_build_duration: 120
    scripts: 
      - name: Running Builder
        script: |
          TERM=xterm
          watch free -m & python streamlit_app.py > /dev/null
